name: Build and Package Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  package-electron-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [14.x]
        include:
          - os: macos-latest
            arch: arm64
            package-script: "package-mac-arm"
          - os: macos-latest
            arch: x64
            package-script: "package-mac-intel"
          - os: windows-latest
            arch: x64
            package-script: "package-win"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Package Electron App
      run: npm run ${{ matrix.package-script }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: release-builds/*
